# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "hello-fory-java"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    directory: "hello-fory-javascript"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
  - package-ecosystem: "pip"
    directory: "hello-fory-python"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
  - package-ecosystem: "gomod"
    directory: "hello-fory-go"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"

